### ISSUE TITLE
How to use tsl-apple-cloudkit in a Vue project

### ISSUE THREAD

**Issue by pcccccc** [typescriptlibs/tsl-apple-cloudkit#28]
### What type of issue is this?

Other

### What is incorrect, incomplete, or missing?

Thank you for tsl-apple-cloudkit, but I don't know how to use it in a Vue project. After running npm i tsl-apple-cloudkit, I'm very sorry, I am a Vue beginner and cannot find more information., I added the following code:

```
import * as CloudKit from 'tsl-apple-cloudkit';

let testsconfig: CloudKit.ContainerConfig = <CloudKit.ContainerConfig>{
  containerIdentifier: "iCloud.org.netzkonform.CloudKitTS",
  apiTokenAuth: {
    apiToken: "825628f17af22927b7e8901ad7ec3db8ada33ce8c31e870b4f09d9e3d3a4b13c",
    persist: false,
    signInButton: {
      id: "apple-sign-in-button"
    },
    signOutButton: {
      id: "apple-sign-out-button"
    }
  },
  apnsEnvironment: "development",
  environment: "development"
}; //from testsconfig.ts

CloudKit.configure({
  containers: [testsconfig],
});
```
The console returns the following error:

```
tsl-apple-cloudkit.js?v=55a242a9:1398 Uncaught 
TypeError: Cannot read properties of undefined (reading 'ArrayBuffer')
    at Object.<anonymous> (tsl-apple-cloudkit.js?v=55a242a9:1398:22)
    at Object.<anonymous> (tsl-apple-cloudkit.js?v=55a242a9:1400:12)
    at t2 (tsl-apple-cloudkit.js?v=55a242a9:41:24)
    at Object.<anonymous> (tsl-apple-cloudkit.js?v=55a242a9:1390:17)
    at t2 (tsl-apple-cloudkit.js?v=55a242a9:41:24)
    at Object.<anonymous> (tsl-apple-cloudkit.js?v=55a242a9:1238:77)
    at t2 (tsl-apple-cloudkit.js?v=55a242a9:41:24)
    at Object.<anonymous> (tsl-apple-cloudkit.js?v=55a242a9:1217:17)
    at t2 (tsl-apple-cloudkit.js?v=55a242a9:41:24)
    at Object.<anonymous> (tsl-apple-cloudkit.js?v=55a242a9:981:352)
Show 22 more frames
```

### What platforms does this issue apply to, if applicable?

Vue

### What did you expect to see?

-

### How did you test this?

-

**Comment by sophiebremer** [comment]
Hello @pcccccc!

Thanks for reaching out.
Your error indicates, that CloudKit JS does not gain access to the `window` object to utilize `ArrayBuffer`. CloudKit JS only supports `CommonJS`, `AMD` (Require.js), and classic global `Window`.

I do not have experience with Vue.js, but I know that it expects ES6 modules. Apple's CloudKit JS (and `tsl-apple-cloudkit`) is not an ES6 module.

- Make sure to load CloudKit.js in you HTML page as mentioned in the README.md.

- Do only `import 'tsl-apple-cloudkit';`.

- Use `window.CloudKit` or `const CloudKit = window.CloudKit;` to proceed.

**Comment by sophiebremer** [comment]
Please let me know, if this works for you, so I can update the README.md with a notice for Vue.js.

**Comment by pcccccc** [comment]
Hello, thank you very much for your response. I first tried
`import 'tsl-apple-cloudkit';`
but found that it still throws an error:

```
tsl-apple-cloudkit.js?v=89b267b5:1398 Uncaught TypeError: Cannot read properties of undefined (reading 'ArrayBuffer')
    at Object.<anonymous> (tsl-apple-cloudkit.js?v=89b267b5:1398:22)
    at Object.<anonymous> (tsl-apple-cloudkit.js?v=89b267b5:1400:12)
    at t2 (tsl-apple-cloudkit.js?v=89b267b5:41:24)
    at Object.<anonymous> (tsl-apple-cloudkit.js?v=89b267b5:1390:17)
    at t2 (tsl-apple-cloudkit.js?v=89b267b5:41:24)
    at Object.<anonymous> (tsl-apple-cloudkit.js?v=89b267b5:1238:77)
    at t2 (tsl-apple-cloudkit.js?v=89b267b5:41:24)
    at Object.<anonymous> (tsl-apple-cloudkit.js?v=89b267b5:1217:17)
    at t2 (tsl-apple-cloudkit.js?v=89b267b5:41:24)
    at Object.<anonymous> (tsl-apple-cloudkit.js?v=89b267b5:981:352)
Show 22 more frames
```

However, using `import * as CloudKit from 'tsl-apple-cloudkit';`and then calling window.CloudKit works fine. The current issue is that the apple-sign-in-button and apple-sign-out-button are not loading correctly. I tried adding:

```
<div id="apple-sign-in-button"></div>
<div id="apple-sign-out-button"></div>
```
both in the Vue template and in index.html, but the divs is empty.

**Comment by sophiebremer** [comment]
Hello!

Thank you for the update.
Great to see that the bundling works!

Make sure to run `let user = await container.setUpAuth();` (and afterwards `container.whenUserSignsIn()`, etc.), or otherwise the buttons will not appear.

**Comment by pcccccc** [comment]
> Hello!
> 
> Thank you for the update. Great to see that the bundling works!
> 
> Make sure to run `let user = await container.setUpAuth();` (and afterwards `container.whenUserSignsIn()`, etc.), or otherwise the buttons will not appear.
Hello, I have followed the instructions and called the methods let user = await container.setUpAuth(); and container.whenUserSignsIn(). The console can return CloudKit error messages, but the buttons are still not displaying correctly (the div's width and height are still 0). I may need to conduct more attempts.

**Comment by pcccccc** [comment]
Hello, after checking, I can now use tsl-apple-cloudkit normally. Thank you very much!

If you need, I can push a working demo.
