### ISSUE TITLE
Environment types are set incorrectly

### ISSUE THREAD

**Issue by c0rv0s** [typescriptlibs/tsl-apple-cloudkit#8]
The environment types for the CloudKit class are set to 
`'DEVELOPMENT_ENVIRONMENT' | 'PRODUCTION_ENVIRONMENT'`

when it should be 
`'development' | 'production'`

https://cdn.apple-cloudkit.com/cloudkit-catalog/#readme/CloudKit-on-the-web shows the environment variable being used for development

**Comment by sophiebremer** [comment]
Thank you for issue report and PR.
